# Generated by Django 5.1.4 on 2026-03-04 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('etudiant', 'Etudiant'), ('responsable', 'Responsable'), ('admin', 'Admin')], default='etudiant', max_length=20),
        ),
    ]
