# Generated by Django 5.1.4 on 2026-02-25 14:12

import resources.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_alter_courspratique_fichier_zip_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courspratique',
            name='fichier_zip',
            field=models.FileField(blank=True, null=True, storage=resources.models.get_zip_storage, upload_to='cours/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='emploidutemps',
            name='fichier_pdf',
            field=models.FileField(storage=resources.models.get_file_storage, upload_to='emploi_temps/'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='fichier',
            field=models.FileField(storage=resources.models.get_file_storage, upload_to='resources/%Y/%m/'),
        ),
    ]
